// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	entity "github.com/PicPay/go-test-workshop/entity"
	mock "github.com/stretchr/testify/mock"
)

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

// Create provides a mock function with given fields: e
func (_m *Writer) Create(e *entity.Person) (entity.ID, error) {
	ret := _m.Called(e)

	var r0 entity.ID
	if rf, ok := ret.Get(0).(func(*entity.Person) entity.ID); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Get(0).(entity.ID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Person) error); ok {
		r1 = rf(e)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Writer) Delete(id entity.ID) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.ID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: e
func (_m *Writer) Update(e *entity.Person) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Person) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NewWriterT interface {
	mock.TestingT
	Cleanup(func())
}

// NewWriter creates a new instance of Writer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWriter(t NewWriterT) *Writer {
	mock := &Writer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
